### ISSUE TITLE
그룹 관련 오류

### ISSUE THREAD

**Issue by seuha516** [swsnu/swppfall2022-team4#103]
![image](https://user-images.githubusercontent.com/79067549/205438117-2e837936-15c3-4ceb-ac25-df2812f2ffe3.png)

마감일이 지나지 않았는데도 회색으로 뜨고, Post 버튼만 초록색인 버그가 있습니다.

**Comment by blackruby02** [comment]
네 저도 작업하다 확인해서 현 pr에 포함시켜놨습니다! 감사합니다:)
