### ISSUE TITLE
[Testing Session] Feedback 중 할만한 개선사항

### ISSUE THREAD

**Issue by KJYoung** [swsnu/swppfall2022-team4#114]
- [x] 그룹 이름 길면 Overflow
- [x] 커뮤니티 게시글 폰트 고정폭폰트?
- [x] 커뮤니티 게시글 \n 처리
- [x] 사진 용량 5MB 안내 메세지
- [x] 프로필 페이지 스크롤?
- [x] 글 삭제시 확인 묻기
- [x] 유튜브 링크 새 탭에서 열기
- [x] 그룹 생성에서 기타 운동의 경우, 강도, 반복, 세트 비활성화(기록 참고)
- [ ] 몸무게 유효값 체크
- [ ] 그룹 정보 변경
- [ ] 기록한 운동 내역 수정
- [x] 기록 페이지 Notes 길 경우 디자인
- [ ] 메인 페이지 차트 크기 조절?
- [x] 그룹 운동 인증에서 표의 헤더랑 아래 행들 정렬 맞추기(grid view 사용하면 편함)
- [x] 기록 복사 1900년
- [ ] 그룹 가입 버튼 크기?
- [ ] 위임 수락?

그외(나중에)
- [ ] 태그 신고, 삭제
- [ ] 커뮤니티 메인에서 태그 필터링 개선

**Comment by seuha516** [comment]
- [ ] 글 등록할 때 루틴 선택이 안 되는 오류?
- [x] 태그 목록에서 태그 클릭으로 필터링

**Comment by seuha516** [comment]
저는 아래 TODO는 안 해도 될 것 같습니다.

- 몸무게 유효값 체크: 이미 체크가 되고 있고, 안내 메시지를 추가하면 오히려 지저분해짐. 현재 유효값 체크 기준은 비정상적으로 낮은 값과 높은 값을 입력하는 것을 방지하고 있음. (키 80-300, 몸무게 20-300, 나이 3-)
- 그룹정보 변경, 운동내역 수정, 차트크기 조절, 위임 수락, 태그 신고 및 삭제: 남은 시간 내에 추가하기 어려우며 필수적이지 않은 기능
- 그룹 가입 버튼 크기: 지금 디자인도 괜찮다고 생각합니다.

**Comment by jihyungKo** [comment]
- 기록 운동 내용 수정 관련: 삭제하고 다시 만든 후에 드래그 앤 드롭으로 움직여도 괜찮을 것 같아서 수정은 굳이 추가하지 않아도 될 것 같습니다.
