### ISSUE TITLE
[FIX] 웹브라우저에서 django 접속 문제

### ISSUE THREAD

**Issue by jihyungKo** [swsnu/swppfall2022-team4#26]
### 문제상황
- `127.0.0.1:8000/` 로 직접 django를 호출할 때 token 오류 문제 발생(프론트에서 호출 시에는 정상 작동)

### 임시방편
- `localhost:8000/` 으로 접속 시 잘 작동(아닌 경우도 있음)
- `settings.py` > `MIDDLEWARE` > `'utils.jwt_middleware.JsonWebTokenMiddleWare'` 삭제

### 예상원인
- localhost는 127.0.0.1로 redirect하는 과정에서 인증 정보 변경됨
- request.user 정보가 바뀜

### 에러 상황
- unathorized error 발생
- message: "토큰이 올바르지 않습니다"

![error](https://ifh.cc/g/J5bPfn.png)

**Comment by KJYoung** [comment]
승하님이 해결하셨습니다.
