### ISSUE TITLE
users/views.py profile_post 버그

### ISSUE THREAD

**Issue by seuha516** [swsnu/swppfall2022-team4#53]
![image](https://user-images.githubusercontent.com/79067549/201074441-0cb40971-ccad-4a8f-8b18-0aa0f46eb330.png)

마이페이지에서 작성 글, 댓글, 스크랩을 가져오는 과정 중에 500 에러가 납니다
문제가 된 부분은 line 299의 `scraps_serializable[index]["comments_num"] = posts[index].get_comments_num()`입니다.
posts[index] 부분에서 인덱스 오류가 생기는데, 이 부분 확인해주시면 감사하겠습니다.
print로 디버깅해보니 scraps_serializable는 11개인데 posts가 10개네요

**Comment by seuha516** [comment]
데이터를 한번 초기화하니까 괜찮아지긴 했습니다

**Comment by KJYoung** [comment]
로컬에서 수정을 저거 관련해서 했긴 했는데 아직커밋을 안한걸 수도 있어서한번 확인해보겠습니다 감사합니다!

**Comment by KJYoung** [comment]
https://github.com/swsnu/swppfall2022-team4/pull/49/commits/9585d277c59619204c02c07967014bc0ed2771fc
위 커밋에서 해결이 됐었던 문제인데 제가 PR merge를 안해서 생긴 문제같습니다.
일단 지금 PR을 draft에서 활성화로 변경할테니 리뷰 후 머지해주시면 감사하겠습니다!

**Comment by KJYoung** [comment]
https://github.com/swsnu/swppfall2022-team4/pull/49
위 PR로 해결되었습니다.
