### ISSUE TITLE
[BUG] 비로그인 상태에서 로그인이 필요한 페이지로 접근.

### ISSUE THREAD

**Issue by KJYoung** [swsnu/swppfall2022-team4#59]
비로그인 상태에서 로그인이 필요한 페이지로 접근할 때, `토큰이 올바르지 않습니다` alert가 최대 3번(http://localhost:3000/post의 경우)까지 나오는 걸로 확인했는데, 이를 한 번만 나오도록 제한할 방법이 있을까요?

**Comment by seuha516** [comment]
한번만 나오게 하려면 모든 페이지에서 dispatch를 두 번 이상 보내면 안 되기 때문에, 그 부분은 그냥 메시지를 끄는게 좋을 것 같습니다.

**Comment by seuha516** [comment]
에러가 뜰만한 부분에서 alert를 모두 제거하는 방법 외에 딱히 떠오르지가 않네요 ㅠㅠ

**Comment by KJYoung** [comment]
넵넵 급한 문제는 아니라 일단 고민해보는 목적에서 issue 남겨두고자 했습니당 천천히 고민해보죠

**Comment by KJYoung** [comment]
alert를 거의 없앴기 때문에 이 문제는 해결된 것 같습니다.
