### ISSUE TITLE
[TEST] Container testing

### ISSUE THREAD

**Issue by blackruby02** [swsnu/swppfall2022-team4#61]
#57 
commit : 84cd60cb94d94a70db751fafbc125529ceccf6ee
<img width="599" alt="KakaoTalk_Photo_2022-11-12-17-12-42" src="https://user-images.githubusercontent.com/112922554/201465117-845d97c7-1c57-421a-a127-1aa367621d28.png">
provider 내에 엘리먼트가 랜더링 되는 게 아니라 위 사진 내용만 랜더링 되는 문제 해결에 어려움을 겪고 있습니다...

**Comment by KJYoung** [comment]
제가 그 branch에 방금 commit한 내용을 보시면 알 수 있을텐데, `GroupList.tsx`의 `useEffect`에서 `dispatch(groupActions.getGroups());`를 해도 redux state에 영향이 없으므로(`mockDispatch`이기 때문), `useSelector`에서 잡아오는 값이 무효해서 `<Loading />`이 나오기 때문입니다. `act( ... )`를 통해 `group/getGroupsSuccess`를 호출해주면서 payload로 그것이 불러왔어야할 payload를 넣어줘야 `useSelector`에 유효한 값이 잡히게 됩니다.

제가 `test/community` branch에서 작업한 내용을 참고하셔도 될 것 같아요.
