### ISSUE TITLE
Sprint 4 피드백

### ISSUE THREAD

**Issue by seuha516** [swsnu/swppfall2022-team4#90]
@KJYoung 
소셜 로그인 후 정보를 입력하는 창에서 입력한 nickname이 반영되지 않는 것 같은데 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/79067549/204075741-60f21b26-9e11-479c-a772-1296537b7cb2.png)
페이지 겹침 문제

@jihyungKo 
![image](https://user-images.githubusercontent.com/79067549/204074897-b14ae201-dda2-410a-b373-523a2ec9ee8b.png)
노트 밑부분이 잘리는 문제가 있습니다.
이런 경우 수정 버튼이 보이지 않기도 합니다.

![image](https://user-images.githubusercontent.com/79067549/204074939-3901f3e7-38e7-4d9e-b6e8-190be38c8880.png)
3번째 이미지부터 첨부가 됐는지 확인이 안 됩니다.
이미지 개수를 제한하거나 스크롤을 추가하는 식으로 개선하는게 좋아보입니다.

![image](https://user-images.githubusercontent.com/79067549/204074971-240934d6-bcba-4cd2-88b1-1312fa5e9aef.png)
이미지와 겹칩니다.

![image](https://user-images.githubusercontent.com/79067549/204075265-6ee4bc2a-3aae-49b9-b222-8d9b1cf6e233.png)
빈 칸이나 0인 상태에서도 추가가 됩니다.

![image](https://user-images.githubusercontent.com/79067549/204075342-4e82228a-c6f1-423a-bf9f-314853757f99.png)
오류가 생긴 element가 삭제를 눌러도 삭제되지 않습니다.

![image](https://user-images.githubusercontent.com/79067549/204075294-411231b0-a4ce-4bf5-b692-8d19568c82b3.png)
추가한 후에도 운동종류 선택이 그대로 남아있지만, 선택하지 않은 것으로 처리되고 있습니다.

![image](https://user-images.githubusercontent.com/79067549/204075320-0ffcc988-deba-4df7-8c29-5fd75151a2b4.png)
취소 버튼, 저장 버튼의 의미가 궁금합니다.

![image](https://user-images.githubusercontent.com/79067549/204075413-11e082be-e063-4506-ae40-5bd7c2fd252a.png)
루틴 부분 디자인이 필요해보입니다.

![image](https://user-images.githubusercontent.com/79067549/204075463-0afb28e0-a480-4e07-986b-57cc82d9d005.png)
추가할때마다 늘어나는 것보다 max-height를 정하고 스크롤을 추가하면 좋겠습니다.
(루틴 페이지에서도 마찬가지입니다)

루틴 이름을 변경하거나 루틴을 삭제하는 기능이 있으면 좋겠습니다.

@blackruby02 
Group seed 함수를 추가해 주세요.

![image](https://user-images.githubusercontent.com/79067549/204075530-aefc2e69-1545-41b9-a181-bab07472c987.png)
이 부분 글자나 요소 배치가 좀 더 깔끔했으면 좋겠습니다.

![image](https://user-images.githubusercontent.com/79067549/204075559-d0782ca6-7e49-4717-a976-421a5b2e4a95.png)
텍스트를 조금 다듬어주세요.

![image](https://user-images.githubusercontent.com/79067549/204075585-5a714ff7-65ca-4ade-812f-bdd482f6bf8c.png)
추가한 후에도 운동종류 선택이 그대로 남아있지만, 선택하지 않은 것으로 처리되고 있습니다.

그룹 채팅으로 navigate하는 버튼을 만들어주세요.

그룹 삭제 버튼에 window.confirm을 넣어주세요.

그룹을 생성할 때 이미 지나간 일자로 마감일을 설정하지 못하게 해 주세요.

![image](https://user-images.githubusercontent.com/79067549/204075711-059c138f-87be-4480-b7ca-bcd5bf93f106.png)
버튼 배치를 조절해주세요.

인증 기능을 완성해주시고, 그룹 멤버 기능에서 멤버를 클릭하면 profile로 이동할 수 있는 기능을 추가해주세요.

**Comment by KJYoung** [comment]
위 내용 중 저와 관련된부분은 해결되었습니다.
