### ISSUE TITLE
User 관련 에러

### ISSUE THREAD

**Issue by jihyungKo** [swsnu/swppfall2022-team4#96]
갑자기 에러가 발생해서 issue 남깁니다. 왜 이런진 모르겠는데 두 번 클릭하면서 요청이 두 번 들어갔는지 같은 유저 정보가 두 개 생성되면서 multiple user 에러가 떴습니다. 한 번 확인해봐도 좋을 듯합니다!
![dd](https://ifh.cc/g/1f9ngk.png)

**Comment by seuha516** [comment]
회원가입을 두 번 눌러서 이렇게 된 건가요, 아니면 admin 페이지에서 생성을 2번 눌러서 이렇게 된 건가요?
