### ISSUE TITLE
[FEAT] Group ++ cert

### ISSUE THREAD

**Issue by KJYoung** [swsnu/swppfall2022-team4#97]
++ cert 쪽에서 지금은 인증한 날짜에 색이 칠해지는게 아니라 workout log를 기록하는 날에 색이 칠해져 있는데 인증한 날에 칠해지는게 좀 더 보기 좋을 것 같아요! 이거는 천천히 수정해도 상관없을 듯 해서 이 PR 마무리하고 다음 PR에서 작업하면 좋을 것 같습니다!

_Originally posted by @jihyungKo in https://github.com/swsnu/swppfall2022-team4/issues/95#issuecomment-1330693142_

**Comment by blackruby02** [comment]
@KJYoung @jihyungKo 
다른 수업 팀플이 이제야 끝나 확인이 늦었습니다 pr 확인했고 다음 pr 때 포함해서 작업하겠습니다 감사합니다:)
