### ISSUE TITLE
Sprint5 PR1 피드백

### ISSUE THREAD

**Issue by seuha516** [swsnu/swppfall2022-team4#98]
@KJYoung 
![image](https://user-images.githubusercontent.com/79067549/204952342-35a9b9c7-a344-4472-a8e7-a505eb4e550f.png)
- 바뀐 게시글처럼 댓글도 높이를 약간 늘리면 좋겠습니다.

![image](https://user-images.githubusercontent.com/79067549/204954454-076a8b53-1aca-4c6c-beed-ac30e34cb82b.png)
- 운동정보 탭 아래 padding을 약간만 추가해주세요

![image](https://user-images.githubusercontent.com/79067549/204954525-784812c0-ae5f-4db4-b0b4-6350fb8f933e.png)
- 이 부분 글씨 잘리는걸 해결할 수 있을까요?

![image](https://user-images.githubusercontent.com/79067549/204954668-1e8cd21c-95a7-4108-8ab8-166b45e27663.png)
- 별 표시는 추후에 즐겨찾기 기능을 추가하시는 부분인가요?
- 태그된 그룹이 없을 시 별도 텍스트 표시

![image](https://user-images.githubusercontent.com/79067549/204956106-121186e6-392f-40e1-a708-49877bc8af6e.png)
- 그룹 post 이 부분 위에 "Group Post" 등의 텍스트를 추가하고, 그룹 디테일 페이지로 돌아갈 수 있는 Back 버튼을 추가하면 좋겠습니다.

@jihyungKo 
- 운동 기록을 추가하는 seed도 만들 수 있으실까요? 

![image](https://user-images.githubusercontent.com/79067549/204953003-c7d71a48-b905-46c9-8875-7ae77685015f.png)
- 기록에서 이미지 추가 시 오류가 뜹니다.

![image](https://user-images.githubusercontent.com/79067549/204953120-29498608-dee3-48dc-8a27-067408d4f603.png)
- 취소를 누르면 기존에 있던 값까지 초기화돼서 빈 칸이 됩니다.

![image](https://user-images.githubusercontent.com/79067549/204953356-1afc3504-6121-4f97-b8d1-c4eff6d09e6c.png)
- 창 높이가 줄어들면 밑부분이 잘리는 오류가 남아있습니다.

![image](https://user-images.githubusercontent.com/79067549/204953503-a4ad2e6f-4fa1-41ad-b806-73914bf18949.png)
- 이 부분을 계속 늘어나게 하지 말고 스크롤을 추가할 수 있을까요?

![image](https://user-images.githubusercontent.com/79067549/204953625-27ed2407-8a95-4850-beaa-fa7547db4d01.png)
- 기록을 추가하지 않았으면 내보내기 버튼을 비활성화하는게 좋을 것 같습니다.
- 불러오기 버튼에 hover가 적용되지 않았습니다.
- 저번에 저장 버튼을 빼기로 했던 것 같은데 맞다면 빼주시는게 좋겠습니다.

![image](https://user-images.githubusercontent.com/79067549/204954030-2010afde-f131-41bb-935f-04d402777640.png)
- 루틴 페이지 디자인
- 스크롤 추가
- PR에서 루틴 edit, 루틴 이름이 완료됐다고 되어있었는데 아직 반영이 안 된 것 같습니다.

@blackruby02 
- 그룹을 추가하는 seed 함수를 만들어주세요.

![image](https://user-images.githubusercontent.com/79067549/204954931-a8b29337-26c0-4d24-a2d3-2d4c61941c9a.png)
- 이미지 제거 및 디자인 개선 필요

![image](https://user-images.githubusercontent.com/79067549/204954985-498b835c-7f75-4913-b804-2d8250972cc0.png)
- 버튼 배치 정리 필요

![image](https://user-images.githubusercontent.com/79067549/204955054-180d3321-9730-4752-aca1-d3a8285f4259.png)
- 배치 정리 필요

![image](https://user-images.githubusercontent.com/79067549/204955104-4fd1af70-988e-4fb3-aec6-4600f5ab673f.png)
- 여기 간격을 조금 줄여주세요.

![image](https://user-images.githubusercontent.com/79067549/204955137-c7c9f5b5-21ca-4b3b-8804-1c93ca0a18fa.png)
- 여기는 간격을 조금 추가해주세요.

![image](https://user-images.githubusercontent.com/79067549/204955291-1c31bfb2-279f-434c-ba97-65d1e2abd591.png)
- 텍스트를 정리해주세요. category는 빼도 될 것 같습니다.

![image](https://user-images.githubusercontent.com/79067549/204955413-fd13028c-029e-4791-80d3-65f08935b048.png)
- 아무 요소가 없어도 스크롤이 뜹니다.
- 이미 인증한 fitelement를 다시 인증하려 하면 alert로 알려주는게 좋을 것 같습니다.

![image](https://user-images.githubusercontent.com/79067549/204955598-2e3393dc-83e3-44d1-9a65-dd7cc37bcc0d.png)
- 이 버튼이 클릭 가능 상태인게 불필요하다고 생각됩니다.
- 버튼을 빼고 "가입 수락 대기중..." 등의 텍스트로 바꾸는게 좋을 것 같습니다.

- 채팅 버튼 누르면 /group/chat/(그룹 id)/로 리다이렉트해주세요. 지금은 /chat/(그룹 id)/로 이동되고 있습니다.

![image](https://user-images.githubusercontent.com/79067549/204956025-ab588060-df3e-491b-9644-875d1f711192.png)
- Cert_days를 사용자가 이해하기 쉽게 바꾸는게 좋겠습니다.
- 클릭하면 유저 프로필로 이동하는 기능을 추가해주세요.

- 그룹 삭제 버튼을 누르면 "삭제하시겠습니까?" 가 뜨는데, "정말 그룹을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다." 와 같이 자세히 쓰면 좋겠습니다.
- 그룹 탈퇴에도 마찬가지로 confirm을 추가해주세요.

![image](https://user-images.githubusercontent.com/79067549/204956321-35c70d22-3a04-4112-99c2-5309f0dee44b.png)
가입 요청이 없으면, 요청이 없다는 텍스트를 가운데에 띄우면 좋겠습니다.

**Comment by KJYoung** [comment]
제 관련 부분은 해결됐습니다.
